# vi:syntax=zsh
# zshrc

[[ $- != *i* ]] && return


# cd
setopt AUTO_CD
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt CDABLE_VARS

#completion
autoload -Uz compinit; compinit
_comp_options+=(globdots)

#history
setopt HIST_SAVE_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS
#setopt SHARE_HISTORY
setopt EXTENDED_HISTORY
setopt HIST_REDUCE_BLANKS
setopt HIST_VERIFY

setopt AUTO_CONTINUE
unsetopt BG_NICE
setopt CHECK_JOBS

# vi mode
setopt VI
export KEYTIMEOUT=1
zmodload zsh/complist
source $ZDOTDIR/cursor_mode
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history


# Enable colors for ls, etc.
eval $(dircolors -b $XDG_CONFIG_HOME/dircolors)

source $ZDOTDIR/zprompt

source $ZDOTDIR/aliases

source $ZDOTDIR/ex

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-background-notify/bgnotify.plugin.zsh

# oh my zsh
#plugins=(colored-man-pages docker extract golang)
#source $ZSH/oh-my-zsh.sh

# rehash after pacman hook
TRAPUSR1() { rehash }
